---
name: release

on:
  release:
    types:
      - published

env:
  PIP_CACHE_DIR: ~/.cache/pip
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Python runtime versions supported by AWS
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
    steps:
      - uses: actions/checkout@v2
      - name: Build the base Lambda Docker image
        run: |
          docker compose build \
            --build-arg PY_VERSION=${{ matrix.python-version }} \
            --build-arg FILE_NAME=${{ github.event.repository.name }} \
            build_deployment_package
      - name: Generate the Lambda deployment package
        run: docker compose up build_deployment_package
      - name: Upload the generated Lambda deployment package as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ github.event.repository.name }}-\
            py${{ matrix.python-version }}-\
            ${{ github.ref_name }}"
          path: "${{ github.event.repository.name }}.zip"
      - name: Setup tmate debug session
        uses: mxschmitt/action-tmate@v3
        if: env.RUN_TMATE
